apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nodejs241108-gitops
  description: This is GitOps manifest for nodejs241108   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: nodejs241108
    backstage.io/kubernetes-id: nodejs241108 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: nodejs241108-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nodejs241108
