apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nodejs241108
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs241108 
  name: nodejs241108
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nodejs241108 
